name: CI
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install Package manager
        run: npm install pnpm
      - name: Install Packages
        run: pnpm install
      - name: Check Lint
        run: npx eslint
      - name: Check Simple Build
        run: pnpm build
