name: CI
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install Packages
        run: npm install
      - name: Check Lint
        run: npx eslint
      - name: Check Simple Build
        run: npm run build
